### ISSUE TITLE
SIXEL handling could be better

### ISSUE THREAD

**Issue by schrmh** [odknt/st#2]
Hi,
I played around a bit with your st version and it looks like it is still somewhat lacking when it comes to SIXEL.
Did you fix anything some previous attempts at SIXEL for st did wrong?

I would suggest you to take a look at the SIXEL patch within https://github.com/bakkeby/st-flexipatch/ since that is more mature in my opinion, while still not perfect (https://github.com/bakkeby/st-flexipatch/issues/30).

Your st seems to have problems with SIXEL images disappearing when scrolling and for some reason I could not even start nvim to test if SIXEL displayed in :terminal.
Also drawing example and gif with img2sixel don't seem to work.
Maybe other things as well.

**Comment by odknt** [comment]
Thanks for the report.

I know that my repository have SIXEL-related issues, but they have been neglected due to the fact that I do not already use SIXEL-related features.

To be honest, the main purpose of this repository is to input Japanese, so the other features are a bonus for me.
So I may remove SIXEL support in this repository the next time I sync to upstream code.

You are right, it is better to look for another project if you want to use SIXEL features as there are other excellent projects out there.

Edit: If I get motivated about SIXEL I will help with projects like bakkeby/st-flexipatch etc.
I like to keep my projects simple.

**Comment by schrmh** [comment]
Thanks for that answer.
Maybe the next time you work on your st fork you can add a note to the README about the state of SIXEL support (in case you keep it at all) — and maybe mention st-flexipatch then.
Feel free to close the issue when you updated it.
